### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by djstrong** [ruby-rdf/rdf-raptor#22]
I encounter memory leak with rdf/raptor
RDF::Reader.open('dbpedia', :format => :nt) do |reader|
  reader.each_statement do |statement|
  end
end

I am using ruby 2.2.0.

**Comment by dwbutler** [comment]
Hi,

Tracking down a memory leak would involve running the specific code that is giving you trouble and looking for areas of the code where memory is not freed. The specific file you're reading would be helpful.

Note that it is normal for Ruby to allocate memory for itself and never free it back to the operating system.

**Comment by djstrong** [comment]
Hi,

probably it was http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/en/instance_types_en.nt.bz2 or http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/en/long_abstracts_en.nt.bz2

**Comment by dwbutler** [comment]
I downloaded `instance_types_en.nt`. Uncompressed, it's a huge file - 3.9 GB. I modified memtest.rb to:

```ruby
RDF::Reader.open("etc/instance_types_en.nt").each(&:inspect)
```

When I ran valgrind against this file (there is a custom rake task, `bundle exec rake memtest`) I didn't find any evidence of a memory leak.

I would expect any Ruby process to allocate tons of memory just to read this file. Ruby won't necessarily choose to do garbage collection enough times to keep your process' memory from growing huge.

If you want to contain memory usage within certain limits, the best thing to do is tune Ruby's garbage collector. You can also look into using the raw raptor data instead of converting into Ruby `RDF::Statement`s. You can work with raw statements by calling `each_statement(raw: true)`. This will avoid copying the data into Ruby data structures, and the C data should be freed immediately after use by FFI.
