### ISSUE TITLE
[Bug] Segmentation fault when parsing very big files

### ISSUE THREAD

**Issue by fr0gs** [ruby-rdf/rdf-raptor#25]
When I execute a very big **construct** query form against a virtuoso db the sparql client and start processing it via:

```
      RDF::Writer.open("/app/output.ttl") do |writer|
        query(construct_query).each_statement do |statement|
          writer << statement
        end
      end
```

And after a while I receive a segfault. Stacktrace can be found [here](https://gist.github.com/fr0gs/bdfd0e682885337525717e090225f110).

I tested the same construct in the virtuoso web endpoint and executes properly.

**Comment by dwbutler** [comment]
Hi, can you provide a copy of the `output.ttl` file so I can try to reproduce the issue? Thanks!

**Comment by fr0gs** [comment]
Hello,

I cannot provide the copy as the data is not public. However, for this **construct** query:

```
CONSTRUCT {
   ?s ?p ?o
}
FROM <http://tempgraph>
WHERE {
   ?s ?p ?o .
} LIMIT 100
```
And printing the **RDF::Statement** before being written:
```
      RDF::Writer.open("/app/output.ttl") do |writer|
        query(construct_query).each_statement do |statement|
          puts statement.inspect
          writer << statement
        end
      end
```
Statements are printed correctly. However for a full query without any limit the statements are not printed and the segfault appears allthesame, which makes me think that the whole query is previously buffered before starting to write into the file.

The size of the file that causes the segfault is **47.2 MB**

**Comment by fr0gs** [comment]
Hello, 

The issue is getting strange. If I limit the **construct** query to 100 elements and print them one by one before writing them into the **output.ttl**: 
```
#<RDF::Statement:0x2ad272a53344(<http://fakeuri/publication/version-21556547-c31f-416b-ad5c-e4fd4febc4f8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fakeuri/publication/publicationVersion> .)>
#<RDF::Statement:0x2ad27206d9c4(<http://fakeuri/publication/version-195acff9-2b3f-4013-9434-d6b9a4dc0af6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fakeuri/publication/publicationVersion> .)>
... etc
```
But when I remove the 100 elements limit in the query, only the first element is printed and right afterwards I get the segfault:
```
#<RDF::Statement:0x2ab6553db61c(<http://fakeuri/publication/version-21556547-c31f-416b-ad5c-e4fd4febc4f8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fakeuri/publication/publicationVersion> .)>
/usr/local/bundle/gems/rdf-raptor-1.99.0/lib/rdf/raptor/ffi/v2/parser.rb:209: [BUG] Segmentation fault at 0x00000000000000
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by dwbutler** [comment]
Taking another look at the stacktrace, the issue happens [here](https://github.com/ruby-rdf/rdf-raptor/blob/1026c59525b381101a0a821c73c8924e55f810ed/lib/rdf/raptor/ffi/v2/parser.rb#L163). This happens when Ruby attempts to read the stream with `sysread` (reading 64 KB at a time), and then the stream is prematurely terminated, resulting in an EOFError being raised. Raptor also seems to be unclear what to do in this case.

My suspicion is that your RDF server is prematurely terminating the connection. Perhaps it isn't configured to return that much data, or encountered some kind of error during processing. As a next debugging step, I would suggest that you try completely reading the output from the server (and perhaps write it to a file) before feeding it into RDF::Raptor.
